// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Author struct {
	Name       string       `json:"name"`
	Book       []*Book      `json:"book"`
	Publishers []*Publisher `json:"publishers"`
}

type Book struct {
	Name      string       `json:"name"`
	Author    *Author      `json:"author"`
	Publisher *Publisher   `json:"publisher"`
	Audios    []*BookAudio `json:"audios"`
	Pages     []*BookPage  `json:"pages"`
	CreatedAt string       `json:"createdAt"`
}

type BookAudio struct {
	CreatedBy    *User  `json:"createdBy"`
	Book         *Book  `json:"book"`
	CursorStarts int    `json:"cursorStarts"`
	CursorEnds   int    `json:"cursorEnds"`
	CreatedAt    string `json:"createdAt"`
}

type BookPage struct {
	Content    string `json:"content"`
	PageNumber int    `json:"pageNumber"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Publisher struct {
	Name    string    `json:"name"`
	Book    []*Book   `json:"book"`
	Authors []*Author `json:"authors"`
}

type RefreshTokenInput struct {
	Token string `json:"token"`
}

type RegisterInput struct {
	DisplayName string `json:"displayName"`
	Email       string `json:"email"`
	Password    string `json:"password"`
}

type User struct {
	DisplayName string  `json:"displayName"`
	Email       string  `json:"email"`
	Avatar      *string `json:"avatar"`
}
